package io.aegis.contracts.events;

import java.time.Instant;
import java.util.Map;
import java.util.UUID;

/**
 * Versioned envelope for every event entering the platform.
 *
 * <p>Delivery is <b>at-least-once</b>: consumers must treat {@code eventId}
 * as the idempotency key (Redis {@code SETNX} + a unique index on the
 * consuming side) so duplicates from producer retries or consumer redelivery
 * are harmless. Ordering is preserved per {@code source} key via Kafka
 * partition keying; out-of-order events are handled by the ingest pipeline's
 * event-time buffer, never by comparing wall clocks.
 *
 * @param schemaVersion envelope schema version ({@link #CURRENT_SCHEMA_VERSION})
 * @param eventId       unique idempotency key, generated by the producer
 * @param eventType     kind of telemetry
 * @param eventTime     producer clock — the only time used for event ordering
 * @param source        "{service}:{instance}" — Kafka message key
 * @param service       logical service name (e.g. checkout-service)
 * @param instance      instance id (e.g. checkout-api-3)
 * @param payload       type-specific body (metric value, log line, health)
 */
public record RawEvent(
        int schemaVersion,
        UUID eventId,
        EventType eventType,
        Instant eventTime,
        String source,
        String service,
        String instance,
        Map<String, Object> payload
) {

    /** Bump when the envelope shape changes; never mutate fields in place. */
    public static final int CURRENT_SCHEMA_VERSION = 1;
}